# Site Settings
title: Club Capra
email: clubcapra@gmail.com
description: >
  Site web du club scientifique capra de l'école de technologie supérieure.
baseurl: ""
url: "http://localhost:4000"
twitter_username: 
github_username:  clubcapra
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM